language: c
compiler: clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y check
before_script:
  - "sudo mkdir -p /opt/local/lib"
  - "sudo ln -s /usr/lib/x86_64-linux-gnu/libfl.a /opt/local/lib/libfl.a"
script: make all && make test
